### ISSUE TITLE
1.20.6 for Trinket Compatible version

### ISSUE THREAD

**Issue by Moravuscz** [Wondiws98/dampening#1]
Hi,
Trinkets for 1.20.6 is out (so is Elytra Trinket).

Just wanted to let you know so you can update the Trinket Compatible version.

Thanks for the awesome mod!

**Comment by Wondiws98** [comment]
yes

**Comment by Wondiws98** [comment]
Thanks for pinging me.

Dampening Trinket Compat 1.20.5/1.20.6 has been released.

[Release](https://modrinth.com/mod/dampening-enchantment/version/ncbpY3WT)
