### ISSUE TITLE
[Update] Minecraft 1.21

### ISSUE THREAD

**Issue by elhertz** [Wondiws98/dampening#2]
Hey! is there a plan for a 1.21 update? thanks!

**Comment by Wondiws98** [comment]
Yes there is, sorry for the late reply.

**Comment by Wondiws98** [comment]
Sorry for the long wait, this was long overdue.

Dampening Enchantment for Minecraft 1.21 is out now!

[1.21 Release](https://modrinth.com/datapack/dampening-enchantment/version/1.0.1)
